version: "3.7"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      DEBUG: 1
      ENVIRONMENT: development
      SECRET_KEY: <GENERATE_OWN_SECRET_KEY>
      USER: <username>
      PASSWORD: <password>
      HOST: db
      PORT: 5432

    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: <password>

volumes:
  postgres_data:
